spring:
  application:
    name: rag
  profiles:
    active: local
  config:
    import: optional:file:.env
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/
      model: qwen3.7-plus
      embedding:
        options:
          model: text-embedding-v4
          dimensions: 768
    chat:
      memory:
        repository:
          jdbc:
            platform: mysql
            initialize-schema: ALWAYS
    vectorstore:
      pgvector:
        # 向量索引类型
        index-type: HNSW
        # 距离度量，余弦值
        distance-type: COSINE_DISTANCE
        # 向量维度
        dimensions: 768
        # 批量处理大小
        max-document-batch-size: 9
        # 启动时是否自动创建表
        initialize-schema: true
        # 创建的表名
        table-name: vector_st
  datasource:
    url: jdbc:postgresql://localhost:5433/rag_test
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080